### ISSUE TITLE
ctrl-number shortcuts not working, cancerttv not showing up in chat settings menu

### ISSUE THREAD

**Issue by pargon-the-wise** [Booom3/CancerTTV#5]
ctrl-# no longer pastes spam into the chat, but only changes browser tabs in Chrome as of today (worked fine 2 days ago). Also cancerttv does not appear in the channel settings menu. Up arrow DOES display previous sent messages in the chat box...

I think twitch may have rolled out an update. Also chrome updated to version 81.0.4044.138

**Comment by Booom3** [comment]
Ugh, how annoying of Twitch.

I'm sorry, though. Since I made this I got a job and a life and such. I barely watch Twitch. And while I would love to maintain it I also have to balance that with a million other things I want to do.
I'll try and find the time to get around to this, but no promises.

**Comment by rrrogaine** [comment]
I submitted a pull request for this: https://github.com/Booom3/CancerTTV/pull/6

**Comment by Booom3** [comment]
@rrrogaine Thank you for this! I will test it tomorrow and get it merged in then. 💜

**Comment by Booom3** [comment]
I merged in the pull request and published on the chrome webstore. I did notice there were a bunch of other things broken, but at least all the hotkeys will work now.
